name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: windows-latest
 
    steps:
    - uses: actions/checkout@v1
      name: Checkout Code
     
    - name: Setup MSBuild Path
      uses: warrenbuckley/Setup-MSBuild@v1
      env: 
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
       
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
      env: 
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
     
    - name: Restore NuGet Packages
      run: nuget restore RecaptchaV3.sln
 
    - name: Build Web App
      run: msbuild RecaptchaV3.sln /p:Configuration=Release
 
    - name: Create nuget Package
      run: nuget pack RecaptchaV3/RecaptchaV3.nuspec

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        path: RecaptchaV3.1.0.0.nupkg